# Generated by Django 4.2.5 on 2023-09-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('departure_km', models.PositiveIntegerField()),
                ('departure_destination', models.CharField(max_length=200)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('return_km', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_traveled', models.PositiveIntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.drivermodel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemodel')),
            ],
            options={
                'verbose_name': 'controlModel',
                'verbose_name_plural': 'controlModel',
                'db_table': 'control',
                'ordering': ['-departure_date'],
            },
        ),
    ]
